### ISSUE TITLE
How i can install?

### ISSUE THREAD

**Issue by 9acca9** [orenskl/HiFiStreamer#1]
sorry, but, i dont know what to do.
Thanks.

**Comment by orenskl** [comment]
Hi, congrats you got issue #1 !!!!!!!

This is still WIP, if you want to build the image you will need to clone the repo and run:

`PROJECT=Generic ARCH=x86_64 make image`

You will need an Ubuntu 20 machine for that. When the build finishes you should get an image in the `target` directory, burn it to a USB and try it.

Currently I have a booting image with Mopidy running, I hope in a few days to have also Mopidy-Iris and I hope to publish the images my self.

Have fun

**Comment by 9acca9** [comment]
> Hi, congrats you got issue #1 !!!!!!!

Lol, thanks for the info!

**Comment by orenskl** [comment]
Hi, I released the first version - you can download the images if you want

**Comment by orenskl** [comment]
I am closing this, please reopen if needed
